import android.content.Context;
import android.content.res.Resources;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Paint;
import android.graphics.drawable.Drawable;
import android.text.TextPaint;
import android.text.style.BackgroundColorSpan;
import android.text.style.CharacterStyle;
import android.text.style.ForegroundColorSpan;
import android.text.style.TextAppearanceSpan;

public final class bzn
{
  public final String A;
  public final String B;
  public final String C;
  public final CharSequence D;
  public final int E;
  public final int F;
  public final int G;
  public final int H;
  public final int I;
  public final int J;
  public final int K;
  public final int L;
  public final int M;
  public final int N;
  public final int O;
  public final TextPaint P;
  public final TextPaint Q;
  public final Paint R;
  public final int S;
  public final int T;
  public final int U;
  public final int V;
  public final TextAppearanceSpan W;
  public final TextAppearanceSpan X;
  public final TextAppearanceSpan Y;
  public final BackgroundColorSpan Z;
  public final Bitmap a;
  public final CharacterStyle aa;
  public final CharacterStyle ab;
  public final CharacterStyle ac;
  public final CharacterStyle ad;
  public final CharacterStyle ae;
  public final TextAppearanceSpan af;
  public final CharacterStyle ag;
  public final TextAppearanceSpan ah;
  public final TextAppearanceSpan ai;
  public final mx aj;
  public final Bitmap b;
  public final Bitmap c;
  public final Bitmap d;
  public final Bitmap e;
  public final Bitmap f;
  public final Bitmap g;
  public final Bitmap h;
  public final Bitmap i;
  public final Bitmap j;
  public final Bitmap k;
  public final Bitmap l;
  public final Bitmap m;
  public final Bitmap n;
  public final Bitmap o;
  public final Drawable p;
  public final Drawable q;
  public final String r;
  public final String s;
  public final CharSequence t;
  public final CharSequence u;
  public final CharSequence v;
  public final CharSequence w;
  public final CharSequence x;
  public final String y;
  public final String z;
  
  public bzn(Context paramContext)
  {
    Resources localResources = paramContext.getResources();
    a = BitmapFactory.decodeResource(localResources, bub.ar);
    b = BitmapFactory.decodeResource(localResources, bub.aq);
    c = BitmapFactory.decodeResource(localResources, bub.aG);
    d = BitmapFactory.decodeResource(localResources, bub.aD);
    e = BitmapFactory.decodeResource(localResources, bub.aC);
    f = BitmapFactory.decodeResource(localResources, bub.aI);
    g = BitmapFactory.decodeResource(localResources, bub.aA);
    h = BitmapFactory.decodeResource(localResources, bub.K);
    i = BitmapFactory.decodeResource(localResources, bub.N);
    j = BitmapFactory.decodeResource(localResources, bub.L);
    k = BitmapFactory.decodeResource(localResources, bub.O);
    l = BitmapFactory.decodeResource(localResources, bub.M);
    m = BitmapFactory.decodeResource(localResources, bub.o);
    n = BitmapFactory.decodeResource(localResources, bub.m);
    o = BitmapFactory.decodeResource(localResources, bub.n);
    p = jr.a(paramContext, bub.U);
    q = jr.a(paramContext, bub.aM);
    r = localResources.getString(buj.eF);
    s = localResources.getString(buj.bt);
    D = localResources.getString(buj.eE);
    t = localResources.getQuantityText(buh.o, 1);
    u = localResources.getQuantityText(buh.o, 2);
    y = localResources.getString(buj.bm);
    z = localResources.getString(buj.cX);
    A = localResources.getString(buj.cW);
    B = localResources.getString(buj.fe);
    C = localResources.getString(buj.da);
    v = localResources.getString(buj.eG);
    w = localResources.getString(buj.de);
    x = localResources.getString(buj.dc);
    E = jr.b(paramContext, btz.L);
    F = jr.b(paramContext, btz.k);
    G = jr.b(paramContext, btz.l);
    H = jr.b(paramContext, btz.H);
    I = jr.b(paramContext, btz.I);
    J = localResources.getInteger(bud.E);
    K = localResources.getDimensionPixelSize(bua.X);
    L = localResources.getDimensionPixelSize(bua.T);
    M = localResources.getInteger(bud.B);
    N = localResources.getInteger(bud.C);
    O = localResources.getInteger(bud.a);
    P = new TextPaint();
    Q = new TextPaint();
    R = new Paint();
    P.setAntiAlias(true);
    Q.setAntiAlias(true);
    R.setColor(localResources.getColor(btz.o));
    S = localResources.getDimensionPixelSize(bua.D);
    T = localResources.getInteger(bud.c);
    U = localResources.getDimensionPixelSize(bua.k);
    V = localResources.getDimensionPixelSize(bua.l);
    W = new TextAppearanceSpan(paramContext, buk.p);
    X = new TextAppearanceSpan(paramContext, buk.o);
    Y = new TextAppearanceSpan(paramContext, buk.a);
    Z = new BackgroundColorSpan(localResources.getColor(btz.b));
    aa = new ForegroundColorSpan(localResources.getColor(btz.L));
    ab = new TextAppearanceSpan(paramContext, buk.b);
    af = new TextAppearanceSpan(paramContext, buk.m);
    ac = new TextAppearanceSpan(paramContext, buk.n);
    ad = new TextAppearanceSpan(paramContext, buk.k);
    ae = new TextAppearanceSpan(paramContext, buk.c);
    ag = new TextAppearanceSpan(paramContext, buk.l);
    ai = new TextAppearanceSpan(paramContext, buk.f);
    ah = new TextAppearanceSpan(paramContext, buk.e);
    aj = mx.a();
  }
}

/* Location:
 * Qualified Name:     bzn
 * Java Class Version: 6 (50.0)
 * JD-Core Version:    0.7.1
 */